[build]
  command = "npm run build"
  publish = "apps/mynextjs/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions.serverless]
  included_files = ["dist/apps/mynestjs/serverless.js"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/serverless"