[build]
  command = "npm run build"
  publish = "apps/mynextjs/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = "dist/apps/mynestjs"
  included_files = ["!*.ts.js"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/serverless"