[build]
  command = "npm run build:netlify"
  publish = "apps/mynextjs/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/serverless/:splat"
  status = 200